[package]
name = "crypto_editor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orion="0.16.0"
termion = "1"
unicode-segmentation = "1"
chrono = "0.4"